apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress
  ports:
    - name: wp_port
      protocol: TCP
      port: 5050
      targetPort: 80
  type: LoadBalancer
  # loadBalancerIP: 172.17.0.X
